implement create event notification based on subscriber policy
Financial-Times/notifications-push pull request #111
Opened 2021-06-22 14:36 UTC by Zarrie

https://financialtimes.atlassian.net/browse/UPPSF-2473

2021-07-01 07:35 UTC, gotha requested changes

2021-07-01 07:35 UTC, gotha commented on consumer/content.go
> +	qHandler.log.
why using `qHandler.log` instead of `monitoringLogger` ?

2021-07-01 07:35 UTC, gotha commented on consumer/mapper.go
> +		var publishCountValue int
you can simplify the code block like this 
```
	eventType = dispatch.ContentUpdateType
	publishCountStr, ok := notificationPayloadMap[publishCountKey].(string)
	if ok {
		publishCount, err := strconv.Atoi(publishCountStr)
		if err != nil {
			return dispatch.Notification{}, fmt.Errorf("could not cast publishCount value to int")
		}

		if publishCount == 1 {
			eventType = dispatch.ContentCreateType
		}

     }
```


or even simpler like this:
```
eventType = dispatch.ContentUpdateType
publishCountStr, _ := notificationPayloadMap[publishCountKey].(string)
if publishCountStr == "1" {
	eventType = dispatch.ContentCreateType
}
```

2021-07-01 07:35 UTC, gotha commented on dispatch/notifications.go
> +	CreateEventConsideredType = "INTERNAL_UNSTABLE"
`INTERNAL_UNSTABLE` is not subscription type.
If anything it should be considered subscription configuration separate from the subscription type. 
Also, why is it defined in `dispatch` package and is only used on `resources` package ?

2021-07-01 07:35 UTC, gotha commented on dispatch/subscribers.go
> +	sendCreateNotifications bool
I think it is better to abstract this a little bit better this. 
If we another notification type (like majorUpdate for example) I dont want to have to have to add another flag called `sendMajorUpdateNotifications` or something like that

2021-07-01 07:35 UTC, gotha commented on dispatch/notifications.go
> +func consolidateNotificationType(notification Notification, isCreateAllowed bool) Notification {
the name of the function does not describe accurately what the function does.
It creates new notification. 
Maybe instead of creating new Notification we can use different `views` of a single struct.

2021-07-01 07:51 UTC, Zarrie commented on consumer/content.go
> +	qHandler.log.
mistake

2021-07-01 07:56 UTC, Zarrie commented on consumer/mapper.go
> +		var publishCountValue int
I didn't want to do this, because I consider bad practice not treating values with their intended types as you suggest, but if you are okay with that and even suggesting it I'm fine doing it - it's not a strong preference anyway

2021-07-01 07:59 UTC, Zarrie commented on dispatch/subscribers.go
> +	sendCreateNotifications bool
I would strongly disagree with this as it's the very definition of premature optimisation. Just as in this PR if we have to add something we do the proper refactoring to enable the change. In this case it would be just replacing the variable with slice of policies, but I see no reason to do the refactoring now and add complexity that may never be needed.

2021-07-01 09:32 UTC, atanasdinov commented on consumer/mapper.go
> +	publishCountKey    = "publishCount"
I'd like to suggest a more unified way of defining the name for these constants. Both of those are used to check the payload of a message yet one is prefixed with `payload` whereas the other one is not, one is called `Flag` whereas the other one is `Key`.

Perhaps add a comment above the block to indicate the following constants are related to the mssage payload and keep the `nameKey` pattern so that `payloadDeletedFlag` is renamed to `deletedKey` or whatever you prefer.

2021-07-01 09:32 UTC, atanasdinov commented on resources/push.go
> +	strings.ToLower(dispatch.CreateEventConsideredType): true,
Only supported content types are listed here. Configuration for `CREATE` events shouldn't be included.

2021-07-01 09:32 UTC, atanasdinov commented on resources/push.go
> +		return retVal, nil
The behaviour is the same but the logic is just more complex. What is the reasoning behind the change?

2021-07-01 09:34 UTC, atanasdinov commented on dispatch/subscribers.go
> +	sendCreateNotifications bool
Perhaps we could just extract an `eventSbscriptionConfig` and use the options "pattern" in order to fill it. Thoughts?

2021-07-05 16:50 UTC, atanasdinov requested changes

2021-07-05 16:50 UTC, atanasdinov commented on resources/push_test.go
> +		RequestHeader  string
I believe this naming is too generic and further updates to the tests might be confusing. Do you think `SubscriptionPolicy` is better?

2021-07-05 16:50 UTC, atanasdinov commented on resources/push_test.go
> +	sub, _ := dispatch.NewStandardSubscriber(req.RemoteAddr, []string{defaultSubscriptionType}, map[dispatch.SubscriberPolicy]bool{dispatch.CreateEventPolicy: false})
Is there a benefit of all these map definitions here and below? Each function could define a single map and use it on each function call:

`policies := map[dispatch.SubscriberPolicy]bool{}`

These tests have no association with the subscription policies and there's also no difference between setting the policy to `false` and omitting it altogether.

2021-07-05 16:50 UTC, atanasdinov commented on dispatch/notifications.go
> +	SubscriptionType string    `json:"-"`
This and the `IsE2ETest` fields are not needed because they are not included with the marshalling.

2021-07-05 16:50 UTC, atanasdinov commented on app_integration_test.go
> +				assert.Equal(t, "data: []\n\n", body, "No NotificationModel Client with type '%s' expects to receive only heartbeat messages.")
Are these changes intended?

2021-07-05 16:50 UTC, atanasdinov commented on consumer/content_test.go
> +	dispatcher.On("Send", mock.AnythingOfType("dispatch.NotificationResponse")).Return()
Could you please verify these tests are actually working? The mock defines the following function:

```
func (m *Dispatcher) Send(notification dispatch.NotificationModel) {
	m.Called(notification)
}
```

2021-07-05 16:50 UTC, atanasdinov commented on consumer/mapper.go
> +		var publishCountValue int
Is this about to be changed according to the suggestions above or will it be left as is?

2021-07-05 16:50 UTC, atanasdinov commented on dispatch/dispatcher.go
> +				entry.Info("Test nm. Skipping standard subscriber.")
Was this log message automatically changed?

2021-07-05 16:50 UTC, atanasdinov commented on dispatch/dispatcher_test.go
> +	m, _ := d.Subscribe("192.168.1.2", contentSubscribeTypes, true, map[SubscriberPolicy]bool{CreateEventPolicy: false})
These tests have no association with the subscription policies and there's also no difference between setting the policy to `false` and omitting it altogether.

It should be possible to use the same map (since it's read-only) for all subscribers as it simplifies the subscription calls: 

`policies := map[dispatch.SubscriberPolicy]bool{}`

(Doesn't apply to `TestCreateNotificationIsProperlyDispatchedToSubscribers`.)

2021-07-05 16:50 UTC, atanasdinov commented on consumer/mapper_test.go
> +	payload := map[string]interface{}{"title": "This is a title", "standout": standout, "type": "Article", "publishCount": 1}
We could benefit from one extra test case where the `publishCount` is not 1 to verify we'd receive an `UPDATE` notification.

2021-07-05 20:23 UTC, Zarrie commented on consumer/mapper.go
> +	publishCountKey    = "publishCount"
Well, I personally find it more easy to aim for simple and descriptive name, though I do not state those are, instead of consistent across some scope names. Also simple clicking on the variables shows where they are used as they are used on a single place, so I don't actually think this introduces any complexity. Also their use is restricted to the given file only.

2021-07-05 20:26 UTC, Zarrie commented on resources/push.go
> +	createEventSubscriptionHeader = "INTERNAL_UNSTABLE"
as the follow up task has to introduce validation of the policies and so on this change will actually be removed and properly validated if the required policies are present. This is more like a mock for testing and does not matter at all since the policies are going to be retrieved via apig soon.

2021-07-05 20:28 UTC, Zarrie commented on dispatch/subscribers.go
> +func MarshalNotificationModelsJSON(n []NotificationModel) ([]byte, error) {
Do you suggest changing the model with the response structure in the history? If not I'm not sure what you suggest. If yes it does not quite make sense because the response is representation depending on the subscriber while I would expect the history to store the actual notification either create or update agnostic of what the subscriber has subscribed for

2021-07-05 20:30 UTC, Zarrie commented on resources/push_test.go
> +		RequestHeader  string
I'm generally not a fan of premature optimisation as this is the very definition of it handling cases which might actually never occur, because confusion would arise only if something else called policies or similar would be introduced, but as this would cost nothing I will change it :)

2021-07-05 20:41 UTC, Zarrie commented
@atanasdinov please tag the team after a review so they have the chance to discuss and leave comments as well

2021-07-06 09:51 UTC, gotha requested changes

2021-07-06 09:51 UTC, gotha commented on consumer/mapper.go
> +	publishCountKey    = "publishCount"
I would prefer to name it either `payloadPublishCountKey`. 
It may be better if `payloadDeletedFlag` is renamed to `payloadDeletedKey` for consistency, but I personally do not think it is that important.

2021-07-06 09:51 UTC, gotha commented on dispatch/dispatcher.go
> +func (d *Dispatcher) Subscribe(address string, subTypes []string, monitoring bool, policies map[SubscriberPolicy]bool) (Subscriber, error) {
I would suggest to use `[]SubscrberPolicy` instead of `map[SubscriberPolicy]bool`.
If you want to mimic Set in go you should use `map[type]struct{}`

2021-07-06 09:51 UTC, gotha commented on dispatch/dispatcher.go
> +func (d *Dispatcher) Subscribe(address string, subTypes []string, monitoring bool, policies map[SubscriberPolicy]bool) (Subscriber, error) {
`SubscriberPolicy` terminology is confusing because it sounds like it is related to API policy. 
For me it would me cleared if we use something like `SubscriptionOption`

2021-07-06 09:51 UTC, gotha commented on dispatch/notifications.go
> +// NotificationModel model
I personally would not rename this to `NotificationModel`, but if you insist to name it that way to distinguish it from `NotificationsResponse` I will squint really hard

2021-07-06 09:51 UTC, gotha commented on dispatch/notifications.go
>  	APIURL           string    `json:"apiUrl"`
Is there a  need to keep the `json` tags ?

2021-07-06 09:51 UTC, gotha commented on dispatch/notifications.go
> +func createNotificationResponse(notification NotificationModel, subscriber Subscriber) NotificationResponse {
I would suggest instead of using the whole subscriber to check if it has specific policy, just pass the policies (a.k.a options) instead. This way it would be slightly more decoupled

2021-07-06 09:51 UTC, gotha commented on app_integration_test.go
> +				assert.InEpsilon(t, heartbeat.Nanoseconds(), delta.Nanoseconds(), 0.05, "No NotificationModel Client with type '%s' expects to receive heatbests on time.")
does this message need to be changed ?

2021-07-06 09:51 UTC, gotha commented on dispatch/dispatcher.go
> +		nr := createNotificationResponse(nm, sub)
ideally pass policies instead of the whole subscriber .

2021-07-06 09:51 UTC, gotha commented on dispatch/subscribers.go
> +	CreateEventPolicy SubscriberPolicy = "CreateEventPolicy"
I would personally type it like this 
```
	CreateEventPolicy SubscriberPolicy = "CreateEvent"
```

2021-07-06 09:51 UTC, gotha commented on resources/history.go
> +		historyJSON, err := dispatch.MarshalNotificationModelsJSON(history.Notifications())
I would expect `/__history` to convert `NotificationModel` to `NotificationReponse`. 
At this point we would not be accepting specific policies and we will return always `UPDATE` but in the future when we want to add this feature it would be trivial.

2021-07-06 09:51 UTC, gotha commented on dispatch/subscribers.go
> +func MarshalNotificationModelsJSON(n []NotificationModel) ([]byte, error) {
:+1:
please check my comment on `resources/history.go`

2021-07-06 09:51 UTC, gotha commented on resources/push.go
> +	createEventSubscriptionHeader = "INTERNAL_UNSTABLE"
I am fine with how it is right now.

2021-07-06 09:56 UTC, gotha commented on resources/push_test.go
> +		RequestHeader      string
I would personally use either `map[string]string` to denote headers or `map[string][]string` to match http.Request Header definition

2021-07-06 15:25 UTC, Zarrie commented on dispatch/dispatcher.go
> +		nr := createNotificationResponse(nm, sub)
hasOption is method of the Subscriber interface. I'd prefer to keep it that way instead of enabling passing only the policies but changing the logic.

2021-07-06 15:29 UTC, Zarrie commented on dispatch/notifications.go
> +func createNotificationResponse(notification NotificationModel, subscriber Subscriber) NotificationResponse {
"hasOption is method of the Subscriber interface. I'd prefer to keep it that way instead of enabling passing only the policies but changing the logic."

If you really insist and consider it better quality code I will do it anyway

2021-07-09 04:51 UTC, gotha commented on consumer/mapper.go
> +		publishCountStr := fmt.Sprintf("%v", notificationPayloadMap[payloadPublishCountKey])
imo, using sprintf to cast to string is (at least ugly). 
I would suggest to use `notificationPayloadMap[payloadPublishCountKey].(string)` as it was originally suggested

2021-07-09 05:01 UTC, gotha commented on dispatch/history.go
> +func (i *inMemoryHistory) Notifications() []NotificationResponse {
storage and presentation logic are mixed here imo. 

inMemoryHistory should accept,store and return `NotificationModel`. 
History should not care about how this data is represented. 
The conversion from `NotificationModel` to `NotificationResponse` should happen in the `history` resource

2021-07-09 05:03 UTC, gotha commented on dispatch/notifications.go
> +func notificationModelToResponse(nm NotificationModel) NotificationResponse {
there is no need for this function, just use `createNotificationResponse` instead. 
There is no point to duplicate the same logic twice

2021-07-09 05:06 UTC, gotha commented on dispatch/notifications.go
> +	if notificationType == ContentCreateType && !hasOption(CreateEventOption, subscriberOptions) {
the function (and the name)`hasOption` implies there is some specific business logic in finding `option`. 
The is not, what is implemented is `array.exists(item)`, go std lib does not have such function on purpose. 
The go way is to use `for`. 
I would personally remove `hasOption` function

2021-07-09 13:54 UTC, atanasdinov submitted a review, later dismissed

2021-07-12 07:05 UTC, gotha commented on dispatch/notifications.go
> +			hasCreateEventOption = true
it is a good practice to break after you have found what you are looking for

2021-07-12 07:14 UTC, gotha commented on resources/history.go
> +			notifications = append(notifications, dispatch.CreateNotificationResponse(n, []dispatch.SubscriptionOption{}))
you can just use `nil` as second parameter to `CreateNotificationResponse`

2021-07-12 07:18 UTC, gotha commented on dispatch/notifications.go
> +	CreateEventConsideredType = "INTERNAL_UNSTABLE"
this is not resolved. 
Why is `CreateEventConsideredType` is defined in `dispatch` package and used only in `resources` package

2021-07-12 12:35 UTC, atanasdinov approved these changes

2021-07-13 05:20 UTC, gotha approved these changes

2021-07-13 05:20 UTC, gotha commented
LGTM, lets do some more manual testing and I think we are ready to go to prod

2021-07-13 10:36 UTC, merged