Subscribe for advanced notifications based on API key policies
Financial-Times/notifications-push pull request #114
Opened 2021-07-22 14:37 UTC by atanasdinov

# Description

## What

Use API key policies in order to subscribe for advanced notifications.

## Why

[JIRA Ticket](https://financialtimes.atlassian.net/browse/UPPSF-2507)

## Anything, in particular, you'd like to highlight to reviewers

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-07-27 11:31 UTC, StephanZahariev commented on resources/validator.go
> +	var keySuffix string
What if we use:
```
keySuffix := key
```

This will log something for the key even if the length is bellow the specified suffix length

2021-07-27 12:38 UTC, atanasdinov commented on resources/validator.go
> +	var keySuffix string
I assume we'd never have such a short key (less than 10 characters) however potentially exposing a key with its full length to the logs might be problematic if later down the road these keys can also have "write" permissions. Thanks for bringing to light.

@gotha what do you think about this suggestion?

2021-07-28 08:27 UTC, StephanZahariev submitted a review, later dismissed

2021-07-28 08:47 UTC, Zarrie approved these changes

2021-07-28 08:56 UTC, gotha requested changes

2021-07-28 08:56 UTC, gotha commented on resources/validator.go
> +	keyPolicies := struct {
parsing "json" as yaml is just weird. 
If it cannot be parsed properly, I would suggest to use regex
```
	r := regexp.MustCompile(`x-policy':\s+'(.*)?'`)
	res := r.FindStringSubmatch("{ 'x-policy': 'orel1,orel2'}")
```

2021-07-28 09:46 UTC, gotha approved these changes

2021-07-28 13:50 UTC, gotha approved these changes

2021-07-28 13:52 UTC, Zarrie approved these changes

2021-07-29 08:59 UTC, merged