Update service to use v3 of kafka-client-go
Financial-Times/notifications-push pull request #126
Opened 2022-04-18 07:09 UTC by dtvalk-ov

Remove obsolete files
Bump go version to 1.17
Fix tests

# Description

## What

[Jira Ticket](https://financialtimes.atlassian.net/browse/UPPSF-3089)
[Updated Kafka Topics Schema](https://lucid.app/lucidchart/72544b1a-9ed2-4b0b-90c5-fb749c6b7fda/edit?invitationId=inv_8845e9ff-a37f-4c7b-9cd4-d8568327064d&page=D0i.FFbelbdG#)

## Why

Copy (if there is one) the text of the original Trello/JIRA ticket in here, with a link back to it for the curious.

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

_Would appreciate a second pair of eyes on the test_  
_I am not quite sure how this bit works_  
_Is there a better library for doing x_  

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2022-04-18 15:30 UTC, atanasdinov requested changes
Let's also consider changing the consumer group name.

Right now we're using the name of the pod which means that new consumer group is created for each one started inside Kubernetes. This will quickly lead to a lot of inactive consumer groups in the MSK cluster which is not ideal.

2022-04-20 15:29 UTC, MiroslavGatsanoga approved these changes

2022-04-20 15:29 UTC, MiroslavGatsanoga commented on consumer/mapper.go
> +		return dispatch.NotificationModel{}, fmt.Errorf("ContentURI does not contain a UUID")
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** Not sure ‏why do you prefer to use `fmt.Errorf` without formatting string and not `errors.New`?

2022-04-21 06:40 UTC, dtvalk-ov commented on consumer/mapper.go
> +		return dispatch.NotificationModel{}, fmt.Errorf("ContentURI does not contain a UUID")
I guess we do it for consistency among services.. I remember getting requested to change errors.New to fmt.Errorf since my first PRs in the team

2022-04-26 10:38 UTC, merged