Feature/uppsf 3271 extract annotation notifications
Financial-Times/notifications-push pull request #133
Opened 2022-11-07 08:02 UTC by martin-stanchev

# Description

## What

Separating the annotations notifications logic and simplifying the service to be more configurable.

## Why

https://financialtimes.atlassian.net/browse/UPPSF-3271

## Anything, in particular, you'd like to highlight to reviewers

Annotations messages were previously validated against the origin, but since they contain `contentURI`s I've removed that logic and added a content uri allowlist for annotations coming from pac.annotations-rw-neo4j and next-video.annotations-neo4j. Let me know if this creates any problems.

## Scope and particulars of this PR (Please tick all that apply)

- [x] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2022-11-07 08:27 UTC, martin-stanchev commented on dispatch/dispatcher.go
> +		} else if notification.SubscriptionType != "" {
The `subscriptionType` variable is set from the Content Type and since it's not present in annotation kafka messages, we should skip the validation. This also will be skipped for lists and pages, where only 1 type is validated and returned.

2022-11-09 09:10 UTC, ilian2233 commented on consumer/consume.go
>  	}
**Question:** Is it possible to have a monitoring event that fails to unmarshal? I think the code will panic in that case.

If true I think the issue can be solved by something like:
```suggestion
        logEntry := h.log.WithTransactionID(tid)
	pubEvent, err := msg.Unmarshal()
	if err != nil {
		logEntry.WithError(err).Error("Failed to unmarshall kafka message")
		return
	}
	
	if h.monitorsEvents {
		logEntry = h.log.WithMonitoringEvent("NotificationsPush", tid, pubEvent.ContentType)
        }	
```

2022-11-09 09:24 UTC, martin-stanchev commented on consumer/consume.go
>  	}
I initially had the log initialising the same way that you suggested, but there are [these test cases](https://github.com/Financial-Times/notifications-push/blob/feature/UPPSF-3271-extract-annotation-notifications/consumer/consumer_test.go#L144) which expect a monitoring event log when the kafka message body is not able to be unmarshalled. If you look at the [old implementation](https://github.com/Financial-Times/notifications-push/blob/master/consumer/content.go#L57), it's also initialised in the same way.

I think this is because if some messages are failing to be processed the monitoring will not be able to catch them if there are no monitoring events and in this case the `pubEvent.ContentType` is set from the kafka header, so in theory there shouldn't be any issues.

2022-11-09 10:47 UTC, ilian2233 approved these changes
LGTM!

2022-11-09 10:47 UTC, ilian2233 commented on consumer/consume.go
> +}
**nitpick (non-blocking):** This can be replaced with `type Set map[string]struct{}`

2022-11-09 12:54 UTC, dtvalk-ov commented on helm/notifications-push/app-configs/annotations-notifications-push_eks_delivery.yaml
> +  name: annotations-notifications-push
Wondering if we should be consistent with the other deployments and use singular form for the service name (annotation-notifications-push) like list-* and page-* 🤔 
For me it sounds better as annotationS-*, but for the sake of consistency.. 😄

2022-11-10 07:19 UTC, martin-stanchev commented on helm/notifications-push/app-configs/annotations-notifications-push_eks_delivery.yaml
> +  name: annotations-notifications-push
I don't mind either. I named it plural because other annotations services like `annotations-rw-neo4j`, `annotations-writer-ontotext` are named plural. I guess it's a case of what we want to be consistent with 😄

2022-11-10 11:52 UTC, ivanruski approved these changes
LGTM.

>Annotations messages were previously validated against the origin, but since they contain contentURIs I've removed that logic and added a content uri allowlist for annotations coming from pac.annotations-rw-neo4j and next-video.annotations-neo4j. Let me know if this creates any problems.

This should not create any problems. `annotations-rw-neo4j` will set the content uri to `http://pac.annotations-rw-neo4j.svc.ft.com/annotations/uuid` when the origin is http://cmdb.ft.com/systems/pac and `http://next-video.annotations-rw-neo4j.svc.ft.com/annotations/uuid` when the origin is http://cmdb.ft.com/systems/next-video-editor. For any other kind of origins the message won't be ingested.

2022-11-10 11:52 UTC, ivanruski commented on consumer/content.go
> -}
**question:** Was that used to handle some old contentType ?

2022-11-10 11:52 UTC, ivanruski commented on consumer/consume.go
> +		if pubEvent.ContentType == "application/json" {
**question:** We will enter this `if` only when the message type is annotations and the `else` for the other instances of the service, right ?

2022-11-10 11:55 UTC, ivanruski commented on dispatch/dispatcher.go
> +		} else if notification.SubscriptionType != "" {
**suggestion (non-blocking):** If we add `MessageType` field to `NotificationMessage` struct, we could use it in `mapper.go` to distinguish the subscription type. In this way we won't treat empty `dispatch.NotificationModel.SubscriptionType` as `dispatch.AnnotationsType`. We would have to check both `Content-Type` and `Message-Type` headers to determine the subscription type though.

2022-11-10 14:35 UTC, martin-stanchev commented on consumer/consume.go
> +		if pubEvent.ContentType == "application/json" {
Yes, in the previous implementation there was also an empty string check, which i think should not be possible in theory. 

Another thought I had was that video (as the content, not the annotations) also is saved as application/json for now, but there are no notifications for videos currently. I guess if that changes this should still work fine.

2022-11-10 14:38 UTC, martin-stanchev commented on consumer/content.go
> -}
As far as i can tell there were some content types (coming from methode i think) that were in the format `application/vnd.ft-upp-article+json; utf8 ...` so this was to remove those 'directives'. 

I haven't found any messages with content types like that so I don't think we need it.

2022-11-10 14:38 UTC, martin-stanchev commented on helm/notifications-push/app-configs/notifications-push_eks_delivery.yaml
> +  CONTENT_URI_ALLOWLIST: "^http://(content|upp)(-collection|-content-placeholder|-notifications-creator)?(-mapper|-unfolder|)(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content|complementarycon
I don't think so. I remember we looked did some research on this when we were rewriting the ingesters, but I don't think we came up with a list of all the URIs. I will check the ingesters though, they are most likely to be up to date

2022-11-10 14:40 UTC, martin-stanchev commented on README.md
> +    && export CONTENT_TYPE_ALLOWLIST="application/vnd.ft-upp-article+json,application/vnd.ft-upp-content-package+json" \
Hmm i guess we don't. They're validated through the article validator with the article schema. I am not sure if it's still present in old published content, but i think it's not needed here anyways

2022-11-10 14:41 UTC, martin-stanchev commented on helm/notifications-push/app-configs/notifications-push_eks_delivery.yaml
> +  CONTENT_URI_ALLOWLIST: "^http://(content|upp)(-collection|-content-placeholder|-notifications-creator)?(-mapper|-unfolder|)(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content|complementarycon
I don't think so. I remember we looked did some research on this when we were rewriting the ingesters, but I don't think we came up with a list of all the URIs. I will check the ingesters though, they are most likely to be up to date

2022-11-10 17:00 UTC, atanasdinov reviewed
Looks great overall! Some things I noticed:
- docker-compose config should also be updated with the `ALLOWLIST` change
- synthetic annotation publications will pass through e.g. `427f2a19-2ae7-47c1-b580-c225fa0a0199`

2022-11-10 17:00 UTC, atanasdinov commented on helm/notifications-push/app-configs/annotations-notifications-push_eks_delivery.yaml
> +  MONITOR_NOTIFICATIONS: "false"
Are there any monitoring logs for annotations? If such exist we might not need to do this.

2022-11-10 17:00 UTC, atanasdinov commented on consumer/mapper.go
> +	if publishCount, ok := notificationPayloadMap[payloadPublishCountKey]; ok && publishCount == "1" {
This will not work. I guess because the `publishCount` is an integer.

2022-11-10 17:00 UTC, atanasdinov commented on consumer/mapper.go
> +	if _, ok := notificationPayloadMap[payloadDeletedKey].(bool); ok {
I'd prefer to have the previous check or a combination of both instead of only verifying whether such field exists and is boolean. This might cause issues if we want to play around with the `deleted` key in the future.

2022-11-10 17:00 UTC, atanasdinov commented on consumer/mapper.go
> +	Resource        string
This is not used anymore.

2022-11-10 17:00 UTC, atanasdinov commented on README.md
> +        --env KAFKA_ADDRESS=localhost:2181 \
```suggestion
        --env KAFKA_ADDRESS=localhost:9092 \
```

2181 is the host of the Zookeeper so this hasn't been updated with the MSK migration.

2022-11-10 17:00 UTC, atanasdinov commented on README.md
> +        --env CONTENT_URI_ALLOWLIST="^http://(methode|wordpress|content)-(article|collection)-(transformer|mapper|unfolder)(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content)/[\\w-]+.*$" \
Could we please have the updated allowlist from the app config?

2022-11-10 17:00 UTC, atanasdinov commented on helm/notifications-push/app-configs/notifications-push_eks_delivery.yaml
> +  CONTENT_URI_ALLOWLIST: "^http://(content|upp)(-collection|-content-placeholder|-notifications-creator)?(-mapper|-unfolder|)(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content|complementarycon
```suggestion
  CONTENT_URI_ALLOWLIST: "^http://(content|upp)(-collection|-content-placeholder|-notifications-creator)?(-mapper|-unfolder|)\\.svc\\.ft\\.com(:\\d{2,5})?/(content|complementarycontent)/[\\w-]+.*$"
```

Can be simplified even further but I'd not take the chances with that many changes in a single PR.

2022-11-10 17:03 UTC, atanasdinov commented on consumer/consume.go
> +		if pubEvent.ContentType == "application/json" {
There's something fishy about it. We allow notifications for video annotations but not videos themselves. Probably something to address with the BAs?

2022-11-10 17:04 UTC, atanasdinov commented on helm/notifications-push/app-configs/annotations-notifications-push_eks_delivery.yaml
> +  name: annotations-notifications-push
I'm with the 🐺 on this one. In the other examples we're talking about `annotations` and in this service we're having `annotation notifications` in mind. See `annotation-notifications-ingester`. It's a nitpick tho.

2022-11-10 17:06 UTC, atanasdinov commented on dispatch/dispatcher.go
> +		} else if notification.SubscriptionType != "" {
The function called in this `else` block i.e. `matchesSubType()` has annotation logic related to it. In any case, a comment in the code would be great to have if we're keeping this check.

2022-11-10 17:09 UTC, atanasdinov commented on helm/notifications-push/app-configs/notifications-push_eks_delivery.yaml
> +  CONTENT_URI_ALLOWLIST: "^http://(content|upp)(-collection|-content-placeholder|-notifications-creator)?(-mapper|-unfolder|)(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content|complementarycon
At a second look, this would always expect a `(-mapper|-unfolder|)`. Is it even working properly prior to this PR?

2022-11-11 07:42 UTC, martin-stanchev commented on helm/notifications-push/app-configs/notifications-push_eks_delivery.yaml
> +  CONTENT_URI_ALLOWLIST: "^http://(content|upp)(-collection|-content-placeholder|-notifications-creator)?(-mapper|-unfolder|)(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content|complementarycon
The `|)` probably is what allows that group to be empty 😄 . I can change it to `(-mapper|-unfolder)?` so it's cleaner, it shouldn't affect how it works.

I was also debating about `(-pr|-iw)?(-uk-.*)?` but I'm not sure if it will affect something. As Vankata mentioned it might be worth to collect all the URIs that we can publish content with so we can update these URIs

2022-11-11 07:56 UTC, ivanruski commented on dispatch/dispatcher.go
> +		} else if notification.SubscriptionType != "" {
Yes, a comment would be fine, because this info will get buried after this PR is merged.

2022-11-11 08:47 UTC, atanasdinov commented on helm/notifications-push/app-configs/notifications-push_eks_delivery.yaml
> +  CONTENT_URI_ALLOWLIST: "^http://(content|upp)(-collection|-content-placeholder|-notifications-creator)?(-mapper|-unfolder|)(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content|complementarycon
Ah, you are probably right about the `|)`... 😄 

`(-pr|-iw)?(-uk-.*)?` was part of the content types published by Methode in the part.

2022-11-11 11:10 UTC, martin-stanchev commented on helm/notifications-push/app-configs/annotations-notifications-push_eks_delivery.yaml
> +  MONITOR_NOTIFICATIONS: "false"
Do you mean if there's anything checking for monitoring logs for annotations? PAM doesn't perform any specific checks for the annotation notifications and annotations in general. I am not sure if there's anything that will check the monitoring logs, but annotations didn't log with monitoring events before so that's why I added this.

2022-11-11 11:10 UTC, martin-stanchev commented on consumer/consume.go
> +		if pubEvent.ContentType == "application/json" {
I'll ask Annie about it!

2022-11-11 13:50 UTC, martin-stanchev commented on dispatch/dispatcher.go
> +		} else if notification.SubscriptionType != "" {
I added the suggestion with the `Message-Type` from the kafka header. Check out how that works and tell me if you like it. I think it's better this way. 

The only issue is with the logic of handling delete notifications. From what I understood there are no delete notifications for annotations, but we should allow delete notifications if the subscription type is empty. This is strange and I am not sure if it makes sense even.

2022-11-11 13:51 UTC, martin-stanchev commented on dispatch/dispatcher.go
> +	if n.Type == ContentDeleteType && notifType == "" {
So `n.Type == ContentDeleteType` should not happen for annotations anyways, and an empty subscription type is also pretty much not possible as far as i can tell

2022-11-14 08:47 UTC, martin-stanchev commented on consumer/consume.go
> +		if pubEvent.ContentType == "application/json" {
So Penko and Annie suggest that we limit video annotation notifications to a x-policy and think about adding video notifications with the same policy in the future. This will make this task much more complex as we don't allow the selection between annotations for different content types, but rather serve all annotations through the endpoint. 

I will add a task that we will discuss on our refinement, but this will go out of scope for this task.

2022-11-14 08:52 UTC, atanasdinov commented on helm/notifications-push/app-configs/annotations-notifications-push_eks_delivery.yaml
> +  MONITOR_NOTIFICATIONS: "false"
Not if there's something checking for such logs automatically but to run manually a Splunk query for annotation publishes with `monitoring_event=true`. If there are such logs we should be able to change the logging here as well without any negative impacts.

2022-11-14 09:26 UTC, martin-stanchev commented on helm/notifications-push/app-configs/annotations-notifications-push_eks_delivery.yaml
> +  MONITOR_NOTIFICATIONS: "false"
Ah okay. Well there seem to be these services -> 

pac-annotations-mapper
annotations-rw-neo4j  
annotations-monitoring-service

The last monitors if the annotations make it to neo4j if i understood it correctly, but I'm not sure if the change here will cause any other issues. @ivanruski what do you think about this?

2022-11-14 10:06 UTC, ivanruski requested changes
LGTM! Just one chore for mapper_test.go

2022-11-14 10:06 UTC, ivanruski commented on consumer/mapper.go
>  	}
**nitpick (non-blocking):** I think that this is better suited right after the line:
```
contentType := getValueFromPayload("type", notificationPayloadMap)
```

2022-11-14 10:06 UTC, ivanruski commented on dispatch/dispatcher.go
> +	if n.Type == ContentDeleteType && notifType == "" {
Can we have `notifType == ""` after the latest change to set `SubscriptionType` based on the Message-Type header?

2022-11-14 12:35 UTC, martin-stanchev commented
@ivanruski I can't reply to your comment for some reason 😄 

> Can we have notifType == "" after the latest change to set SubscriptionType based on the Message-Type header?

Theoretically yes, if Message-Type is not `concept-annotations` and there is no `type` in the kafka body it will be empty. In practice though i don't think this will happen.

2022-11-15 08:21 UTC, atanasdinov commented on README.md
> +    --content_type_allowlist="application/vnd.ft-upp-article+json" --content_type_whitelist="application/vnd.ft-upp-content-package+json" \
```suggestion
    --content_type_allowlist="application/vnd.ft-upp-article+json" \
```

2022-11-15 08:21 UTC, atanasdinov commented on helm/notifications-push/app-configs/annotation-notifications-push_eks_delivery.yaml
> +  API_KEY_POLICIES_ENDPOINT: "t800/policy"
Is this one necessary?

2022-11-15 08:21 UTC, atanasdinov commented on docker-compose.yaml
> +      CONTENT_URI_ALLOWLIST: "^http://(methode|wordpress-article|content)(-collection|-content-placeholder)?-(mapper|unfolder)(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content|complementaryco
Could we also update this allowlist?

2022-11-15 12:29 UTC, ivanruski submitted a review, later dismissed

2022-11-15 13:18 UTC, ilian2233 approved these changes

2022-11-17 16:48 UTC, ivanruski commented on helm/notifications-push/app-configs/annotations-notifications-push_eks_delivery.yaml
> +  MONITOR_NOTIFICATIONS: "false"
The monitor for annotations publishes cares about 3 kinds of `monitoring_event`s , "PublishStart"(logged in `cms-metadata-notifier`), "Map"(logged in `pac/video-annotations-mapper`), and "SaveNeo4j"(logged in `annotations-rw-neo4j`). I think that this change won't affect the annotations monitoring process.

2022-11-17 16:54 UTC, ivanruski approved these changes

2022-11-21 12:42 UTC, atanasdinov approved these changes

2022-11-21 13:12 UTC, ilian2233 approved these changes

2022-11-22 08:44 UTC, merged