Integrate opa as sidecar service
Financial-Times/notifications-push pull request #152
Opened 2024-07-24 14:49 UTC by lokendersinghft

# Description

## What

Integrated OPA as a sidecar service, replacing existing opa library.

## Why

JIRA --> https://financialtimes.atlassian.net/browse/UPPSF-4877

## Anything, in particular, you'd like to highlight to reviewers

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [x] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2024-07-26 10:48 UTC, todor-videv1 requested changes
Right, this is really good. I'm marking it as "Request changes" just for the double call to EvaliateContentPolicy in the dispatcher.go file. Try to check whether we can improve that.

2024-07-26 10:48 UTC, todor-videv1 commented on app.go
> +		evaluator := access.NewOpenPolicyAgent(opaClient, log)
**todo**: Can you please change this to be called opaAgent. Actually check post-publication-combiner for the naming conventions we would, ideally, like to use.

2024-07-26 10:48 UTC, todor-videv1 commented on app.go
> +		evaluator := access.NewOpenPolicyAgent(opaClient, log)
main.go and agent.go in post-publication-combiner

2024-07-26 10:48 UTC, todor-videv1 commented on app_integration_test.go
> +	e := access.GetOPAAgentForTesting(log)
**todor**: When you change the naming of evaluator, this should probaly become a, or oa.

2024-07-26 10:48 UTC, todor-videv1 commented on dispatch/dispatcher.go
> +func NewDispatcher(delay time.Duration, history History, policyEvaluator access.Evaluator, log *logger.UPPLogger) *Dispatcher {
**todo**: Again, this would need changing after you rename the Evaluator interface.

2024-07-26 10:48 UTC, todor-videv1 commented on dispatch/dispatcher.go
> +	})
**suggestion**: I don't like this, I know that it kinda was there but can we think of evaluating the policy only once. Only one call to EvaluateContentPolicy. Basically you can initialize the query with the editorialDesk... it is guaranteed to be there. Then you can check for the publication and if it is missing set it to FT Pink and then attach that to the query. In this way you can send just one request.

2024-07-26 10:48 UTC, todor-videv1 commented on .circleci/config.yml
> +          command:  docker-compose -f docker-compose-tests.yaml up -d --build && docker logs -f test-runner && export TESTS_STATUS_CODE=$(docker inspect test-runner --format="{{.State.ExitCode}}") &&
**praise**: This seems really interesing. Good job to research it and implement it.

2024-07-26 10:48 UTC, todor-videv1 commented on helm/notifications-push/values.yaml
> +  tag: 0.62.0
**idea**: Check for new version.

2024-07-26 10:54 UTC, ilian2233 commented on .circleci/config.yml
> +            - cm-team-github
*nitpick:* Yaml files should end with new line.

2024-07-26 10:54 UTC, ilian2233 commented on go.mod
>  	github.com/Financial-Times/go-logger/v2 v2.0.1
*Suggestion:* We can update the go version here

2024-07-29 06:23 UTC, lokendersinghft commented on app.go
> +		evaluator := access.NewOpenPolicyAgent(opaClient, log)
1. Updated to opaAgent
2. Also renamed files to agent.go and agent_test.go as in post-publication-combiner

2024-07-29 06:23 UTC, lokendersinghft commented on dispatch/dispatcher.go
> +	})
Updated the code to evaluate the policy only once. Also added tests in dispatcher_test.go because of major altering in dispatcher.go

2024-07-29 06:26 UTC, lokendersinghft commented on helm/notifications-push/values.yaml
> +  tag: 0.62.0
Updated version to 0.67.0. Previously, I was hesitant in creating version disparity with opa version while bundling in cm-opa-policy repo. Because it is working fine in dev, I have decide to do the version update.

2024-07-30 10:32 UTC, todor-videv1 commented on dispatch/dispatcher.go
> +				entry.Info("Skipping subscriber due to ", evaluationResult.Reasons)
**issue**: you'll need to format the Reasons array. Try something like this:

`strings.Join(evaluationResult.Reasons[:], ", ")`

2024-07-30 10:33 UTC, todor-videv1 requested changes
The code is fine besides one very minor issue, please fix it and we are done.

2024-07-30 11:42 UTC, todor-videv1 approved these changes

2024-07-30 11:43 UTC, ilian2233 approved these changes

2024-07-30 12:36 UTC, todor-videv1 approved these changes

2024-07-31 04:42 UTC, antoanFT approved these changes

2024-07-31 11:05 UTC, merged